package com.chess.blackbox.moves;

import com.chess.blackbox.ChessTestBase;
import com.chess.root.Board;
import com.chess.root.moves.Move;
import com.chess.root.pieces.Piece;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

/**
 * Black-box tests for castling using EP, BA, and EG.
 *
 * Spec (FIDE Laws 3.8.2): castling is legal only when neither piece has moved,
 * the path is clear, the king is not in check, and the king does not pass through
 * an attacked square.
 *
 * White king sits at e1 (col=4, row=7). King-side rook at h1, queen-side at a1.
 * Castling moves are generated by KingPiece.getCastlingMoves().
 */
public class CastlingTest extends ChessTestBase {

    // Starting position with inner pieces cleared — both castling sides open
    private static final String FEN_BOTH_SIDES_CLEAR =
            "r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1";

    // White: only king-side castling right
    private static final String FEN_KINGSIDE_ONLY =
            "4k3/8/8/8/8/8/8/R3K2R w K - 0 1";

    // White: only queen-side castling right
    private static final String FEN_QUEENSIDE_ONLY =
            "4k3/8/8/8/8/8/8/R3K2R w Q - 0 1";

    // White: no castling rights
    private static final String FEN_NO_CASTLING =
            "4k3/8/8/8/8/8/8/R3K2R w - - 0 1";

    // Bishop on b1 blocking the queen-side path
    private static final String FEN_BISHOP_BLOCKING_QUEENSIDE =
            "4k3/8/8/8/8/8/8/RB2K2R w KQ - 0 1";

    // Knight on f1 blocking the king-side path
    private static final String FEN_KNIGHT_BLOCKING_KINGSIDE =
            "4k3/8/8/8/8/8/8/R3KN1R w KQ - 0 1";

    // White king in check by black rook on e8
    private static final String FEN_KING_IN_CHECK =
            "4r3/8/8/8/8/8/8/R3K2R w KQ - 0 1";

    // Black rook on f8 attacks f1 — king-side path attacked
    private static final String FEN_KINGSIDE_PATH_ATTACKED =
            "5r2/8/8/8/8/8/8/R3K2R w KQ - 0 1";

    // -------------------------------------------------------------------------
    // Equivalence Partitioning
    // -------------------------------------------------------------------------

    /**
     * [EP] Both sides clear, full castling rights: 2 castling moves available.
     * Partition: both castling sides legal.
     * Goal: CastlingMove objects generated for both king-side and queen-side.
     */
    @Test
    public void testBothCastlingMovesAvailable() {
        Board board = createBoard(FEN_BOTH_SIDES_CLEAR);
        List<Move> castlingMoves = getCastlingMoves(board, 4, 7); // e1 white king
        assertEquals("Both castling sides should be available", 2, castlingMoves.size());
    }

    /**
     * [EP] FEN castling right "K" only: 1 castling move, landing on g1 (col=6).
     * Partition: single-side castling rights.
     */
    @Test
    public void testOnlyKingsideCastlingAvailable() {
        Board board = createBoard(FEN_KINGSIDE_ONLY);
        List<Move> castlingMoves = getCastlingMoves(board, 4, 7);
        assertEquals("Only king-side castling should be available", 1, castlingMoves.size());
        assertEquals("King-side castling lands on g1 (col=6)", 6,
                castlingMoves.get(0).getField().getColumn());
    }

    /**
     * [EP] FEN castling right "Q" only: 1 castling move, landing on c1 (col=2).
     */
    @Test
    public void testOnlyQueensideCastlingAvailable() {
        Board board = createBoard(FEN_QUEENSIDE_ONLY);
        List<Move> castlingMoves = getCastlingMoves(board, 4, 7);
        assertEquals("Only queen-side castling should be available", 1, castlingMoves.size());
        assertEquals("Queen-side castling lands on c1 (col=2)", 2,
                castlingMoves.get(0).getField().getColumn());
    }

    /**
     * [EP] No castling rights ("-"): 0 castling moves.
     * Partition: both castling rights forfeited.
     */
    @Test
    public void testNoCastlingRightsYieldsZeroMoves() {
        Board board = createBoard(FEN_NO_CASTLING);
        List<Move> castlingMoves = getCastlingMoves(board, 4, 7);
        assertEquals("No castling rights should yield 0 castling moves", 0, castlingMoves.size());
    }

    // -------------------------------------------------------------------------
    // Boundary Analysis
    // -------------------------------------------------------------------------

    /**
     * [BA] Bishop on b1 blocks queen-side: queen-side castling unavailable.
     * Boundary: piece immediately adjacent to rook blocks that castling side.
     */
    @Test
    public void testBishopBlockingQueensidePreventsQueensideCastling() {
        Board board = createBoard(FEN_BISHOP_BLOCKING_QUEENSIDE);
        List<Move> castlingMoves = getCastlingMoves(board, 4, 7);
        boolean queensidePresent = castlingMoves.stream()
                .anyMatch(m -> m.getField().getColumn() == 2); // c1
        assertFalse("Queen-side (c1) castling should be blocked by bishop on b1",
                queensidePresent);
    }

    /**
     * [BA] Knight on f1 blocks king-side: king-side castling unavailable.
     * Boundary: piece between king and king-side rook.
     */
    @Test
    public void testKnightBlockingKingsidePreventsKingsideCastling() {
        Board board = createBoard(FEN_KNIGHT_BLOCKING_KINGSIDE);
        List<Move> castlingMoves = getCastlingMoves(board, 4, 7);
        boolean kingsidePresent = castlingMoves.stream()
                .anyMatch(m -> m.getField().getColumn() == 6); // g1
        assertFalse("King-side (g1) castling should be blocked by knight on f1",
                kingsidePresent);
    }

    // -------------------------------------------------------------------------
    // Error Guessing
    // -------------------------------------------------------------------------

    /**
     * [EG] King in check: castling must not be available.
     * FIDE rule: castling is illegal while the king is in check.
     * Verified indirectly: king is in check, so Board.getValidMoves() excludes castling.
     * We also confirm the check state via isPieceEndangered.
     * Fault class: castling allowed while in check.
     */
    @Test
    public void testCastlingNotAvailableWhenKingIsInCheck() {
        Board board = createBoard(FEN_KING_IN_CHECK);
        Piece king = board.getField(4, 7).getPiece();
        List<Piece> blackPieces = board.getPieces(true);
        assertTrue("King should be in check in this FEN", board.isPieceEndangered(king, blackPieces));
        // Board.getValidMoves() only adds castling when !check, so 0 castling expected
        List<Move> castlingMoves = getCastlingMoves(board, 4, 7);
        assertEquals("Castling must not be available while king is in check", 0, castlingMoves.size());
    }

    /**
     * [EG] King-side castling path (f1) under attack: king-side unavailable.
     * FIDE rule: king cannot pass through an attacked square.
     * Fault class: pass-through attack not checked during castling validation.
     */
    @Test
    public void testKingsideCastlingUnavailableWhenPathUnderAttack() {
        Board board = createBoard(FEN_KINGSIDE_PATH_ATTACKED);
        List<Move> castlingMoves = getCastlingMoves(board, 4, 7);
        boolean kingsidePresent = castlingMoves.stream()
                .anyMatch(m -> m.getField().getColumn() == 6); // g1
        assertFalse("King-side castling should be blocked when f1 is under attack",
                kingsidePresent);
    }

    /**
     * [EG] Castling move notation: O-O for king-side, O-O-O for queen-side.
     * Goal: PGN notation is correct for both castling types.
     * Fault class: incorrect notation affects PGN export quality.
     */
    @Test
    public void testCastlingMoveNotationIsCorrect() {
        Board board = createBoard(FEN_BOTH_SIDES_CLEAR);
        List<Move> castlingMoves = getCastlingMoves(board, 4, 7);
        boolean hasKingside = castlingMoves.stream()
                .anyMatch(m -> "O-O".equals(m.getPgnNotation()));
        boolean hasQueenside = castlingMoves.stream()
                .anyMatch(m -> "O-O-O".equals(m.getPgnNotation()));
        assertTrue("King-side castling PGN notation should be 'O-O'", hasKingside);
        assertTrue("Queen-side castling PGN notation should be 'O-O-O'", hasQueenside);
    }
}
